### ISSUE TITLE
ARM64 & AMD64 cases are incorrect - swapped?

### ISSUE THREAD

**Issue by lioncubs** [mr-pmillz/pimp-my-shell#25]
ARM64 & AMD64 cases are incorrect - swapped?
For some reason was always DLing the wrong  go CPU type - take a look

─────────────────────────────────────────────────────────────────────────────────────────────┐
localio/localio.go:188: func DownloadAndInstallLatestVersionOfGolang(homeDir string) error { │
─────────────────────────────────────────────────────────────────────────────────────────────┘
 188⋮ 188│    latestGoVersion := string(goversion)
 189⋮ 189│
 190⋮ 190│    switch GetCPUType() {
 191⋮    │    case "AMD64":
    ⋮ 191│    case "ARM64":
 192⋮ 192│        armGoURL := fmt.Sprintf("https://dl.google.com/go/%s.linux-arm64.tar.gz", latestGoVersion)
 193⋮ 193│        dest := fmt.Sprintf("%s/%s", homeDir, path.Base(armGoURL))
 194⋮ 194│        if err = DownloadFile(dest, armGoURL); err != nil {

─────────────────────────────────────────────────────────────────────────────────────────────┐
localio/localio.go:199: func DownloadAndInstallLatestVersionOfGolang(homeDir string) error { │
─────────────────────────────────────────────────────────────────────────────────────────────┘
 199⋮ 199│            return err
 200⋮ 200│        }
 201⋮ 201│
 202⋮    │    case "ARM64":
    ⋮ 202│    case "AMD64":
 203⋮ 203│        amdGoURL := fmt.Sprintf("https://dl.google.com/go/%s.linux-amd64.tar.gz", latestGoVersion)
 204⋮ 204│        dest := fmt.Sprintf("%s/%s", homeDir, path.Base(amdGoURL))
 205⋮ 205│        if err = DownloadFile(dest, amdGoURL); err != nil {
(END)

**Comment by mr-pmillz** [comment]
Good Catch!!!! @lioncubs 

Thank you for pointing this out to me. I'm going to push out a fix for this now 💯

**Comment by mr-pmillz** [comment]
This is fixed now :octocat:  https://github.com/mr-pmillz/pimp-my-shell/commit/a62396714ef63efec19045f6d6f210ca71c9d9ee
@lioncubs

**Comment by lioncubs** [comment]
NP - thnx for the quick fix.
